server:
  port: 9001
  ssl:
    key-store: classpath:cert/6175226_aliyun.ewen.pw.jks
    key-store-password: fXo5r985
    key-store-type: JKS

logging:
  level:
    root: info

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/changdi?useSSL=false&characterEncoding=utf8
    username: wenliang
    password: wenliang

  #   文件上传路径
bizconfig:
  file:
    file_upload_root_path: /home/wenliang/Webs/frontends/wlpt_ng_alain/downloads/

frontendUrls: https://aliyun.ewen.pw:9101  # 前端程序部署地址