spring:
  profiles:
    active: test


  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true  #打开二级缓存
          use_query_cache: true #打开查询缓存，可以缓存列表集合
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE #只有在实体上注解的才能缓存

  #不限制单个文件上传大小
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

  #业务自定义配置
bizconfig:
  user:
  #   管理员角色id
    admin_role_id: admin
    admin_role_name: admin
  #   匿名角色id
    anonymous_role_id: anonymous
    anonymous_role_name: anonymous
  #   管理员用户id
    admin_user_id: admin
    admin_user_name: admin
  #   游客用户id
    guest_user_id: guest
    guest_user_name: guest

  #   序列号相关
  serial_number:
    weixing_name: weixing
    weixing_basis: "[date:yyyy]{4}"

  #   权限
  permission:
    all_permissions: ChangdiPermission.READ,ChangdiPermission.WRITE,ChangdiPermission.CREATE,ChangdiPermission.DELETE,ChangdiPermission.FINISH  #系统支持的权限

  # 资源类型
  resources:
      - name: 我的资源
        path: /resources/myresources
        type: pw.ewen.WLPT.domains.entities.resources.myresource.MyResource
        typeName: MyResource
        description: 我的资源
      - name: 卫星场地
        path: /resources/weixings
        type: pw.ewen.WLPT.domains.entities.resources.weixing.WeixingResource
        typeName: WeixingResource
        description: 卫星场地

  # 系统使用的日期时间格式
  localDateTimeFormat: yyyy-MM-dd HH:mm:ss
  localDateFormat: yyyy-MM-dd
  # 各区id对应Map
  regionMap:
   0: 市属
   1: 黄浦区
   4: 徐汇区
   5: 长宁区
   6: 静安区
   7: 普陀区
   9: 虹口区
   10: 杨浦区
   12: 闵行区
   13: 宝山区
   14: 嘉定区
   15: 浦东新区
   17: 奉贤区
   18: 松江区
   19: 金山区
   20: 青浦区
   21: 崇明区