#server:
#  port: 9001
#  ssl:
#    key-store: classpath:cert/6746214_test.changdi.shssgc.org.cn.jks
#    key-store-password: FNkhrxX9
#    key-store-type: JKS

logging:
  level:
    root: info

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:mysql://mysql:3306/changdi?useSSL=false&characterEncoding=utf8
    username: wenliang
    password: wenliang


bizconfig:
  file:
    # 文件上传路径
    file_upload_root_path: /home/wenliang/Webs/frontends/wlpt_ng_alain/downloads/
    # 卫星场地审核单模板
    weixing_field_audit_template: ./FieldAuditPrintTemplates/weixing.docx
    # 娱乐场地审核单模板
    yule_field_audit_template: ./FieldAuditPrintTemplates/yule.docx
    # vod审核单模板
    vod_field_audit_template: ./FieldAuditPrintTemplates/vod.docx

  # 定时任务相关配置
  schedules:
    # 定时更新资源阅读情况任务
    resource_readed_info:
      # 每隔30分钟执行一次， - 表示禁用
      cron: 0 */30 * * * ?
      do_startup: true

frontendUrls: http://192.168.0.51  # 前端程序部署地址
